spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: b_routes
          uri: lb://news
          predicates:
            - Path=/news/**
          filters:
            - StripPrefix=1
        - id: a_routes
          uri: lb://user
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1